### ISSUE TITLE
you-win.mp3 missing.

### ISSUE THREAD

**Issue by hackling** [davekinkead/battlebots#10]
Game doesn't load due to https://github.com/davekinkead/battlebots/blob/master/game.rb#L19

**Comment by davekinkead** [comment]
Copyright issues on the song so I'm not committing it :(
#1311039 reflects

**Comment by davekinkead** [comment]
https://github.com/davekinkead/battlebots/commit/131103964cf7294c795a70625b794e7eb59b6d50

**Comment by hackling** [comment]
BTW, I own the copyright on `ow.wav` so it's ok to include.
